export interface TranscriptRequest {
  en: string;
  name: string;
  requestFrom: string;
  dateReceived: string;
  program: string;
  nature: string;
  adviser: string;
  dateSent: string;
  by: string;
  notes: string;
  dateReturnAdviser: string;
  dateReturnSalary: string;
  sentTo: string;
}

export const INITIAL_TRANSCRIPT_LOG: TranscriptRequest[] = [
  {
    en: "723311",
    name: "Susan Kang",
    requestFrom: "Teacher",
    dateReceived: "Dec 19 2024",
    program: "Preliminary Multiple Subject",
    nature: "Requesting her District Intern Program transcript from 2003. She holds a clear California credential but has been denied reciprocity in New York as their system shows only exam completion. She needs the transcript to prove she completed the required courses.",
    adviser: "Rene Gaudet",
    dateSent: "Aug 07 2025",
    by: "J. Detar",
    notes: "Office of Teaching Initiatives",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "New York State Education Department"
  },
  {
    en: "1070649",
    name: "Christian Vaca",
    requestFrom: "Teacher",
    dateReceived: "Jun 02 2025",
    program: "Preliminary MMSN/MMD",
    nature: "I hope all is well. I've attached a signed transcript request. Thank you for your assistance.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "Sent to alicia.smith@norris.k12.ca.us",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Norris School District"
  },
  {
    en: "923693",
    name: "Falen Branch",
    requestFrom: "Teacher",
    dateReceived: "Jun 04 2025",
    program: "Preliminary ECSE",
    nature: "Request for an official iCAAP transcript and detailed course descriptions (Student # 923693) for general purposes at LACOE, asking if any forms or fees are required, and requesting the documents be emailed to the name listed on the form.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "Sent to btpintern@lacoe.edu",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "The LACOE District Intern Program"
  },
  {
    en: "1106695",
    name: "Shumaila Hussain",
    requestFrom: "Teacher",
    dateReceived: "Jun 11 2025",
    program: "Preliminary Single Subject",
    nature: "I am requesting the iCAAP transcript for Single subject math. I culminated on 6/3/2025. I was in cohort 123 for single subject math. iCAAP transcript form is attached here.",
    adviser: "Zina Dixon",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "960639",
    name: "Vanessa Beauchemin",
    requestFrom: "Teacher",
    dateReceived: "Jun 19 2025",
    program: "Induction Program",
    nature: "Is there anyway to get official transcript? For employment? Or could I have you email her?",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Jul 09 2025",
    by: "J. Detar",
    notes: "Sent to Riverside Unified School District (RUSD)",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Riverside Unified School District (RUSD)"
  },
  {
    en: "1200187",
    name: "Elizabeth Twomey",
    requestFrom: "Teacher",
    dateReceived: "Jun 26 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Following up again to check on my Induction transcript. Thank you.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 07 2025",
    by: "J. Detar",
    notes: "Sent to Irvine Unified School District (USD)",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Irvine Unified School District (IUSD)"
  },
  {
    en: "1036213",
    name: "Angela Lee",
    requestFrom: "Teacher",
    dateReceived: "Jun 27 2025",
    program: "Preliminary MOD/ESN",
    nature: "Ms.Bonnie, May I please have transcript what I took from iCAAP? I would like to keep for my copy of the transcript.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1193740",
    name: "Braulio Rodriguez",
    requestFrom: "Teacher",
    dateReceived: "Jul 03 2025",
    program: "Preliminary Single Subject",
    nature: "Nothing was stated in the email.",
    adviser: "Zina Dixon",
    dateSent: "Aug 07 2025",
    by: "J. Detar",
    notes: "Long Beach Unified School District",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Long Beach Unified School District"
  },
  {
    en: "1130610",
    name: "Alberto Tercero",
    requestFrom: "Teacher",
    dateReceived: "Jul 08 2025",
    program: "Preliminary MMSN/MMD",
    nature: "I wanted to follow up on whether I can obtain my transcripts from iCAAP.",
    adviser: "Eberardo Rodriguez",
    dateSent: "",
    by: "J. Detar",
    notes: "My response: Please specify where the transcript needs to be sent to at Cal State LA, including mailing address and to whose attention this needs to be addressed to.",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "733100",
    name: "Erik Estrada",
    requestFrom: "Teacher",
    dateReceived: "Jul 15 2025",
    program: "Preliminary Multiple Subject",
    nature: "Good morning, Please find the attached request for transcripts. Thank you, Erik Estrada.",
    adviser: "Rene Gaudet",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "Sent to ed-gradstudies@csulb.edu",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Cal State Long Beach"
  },
  {
    en: "957604",
    name: "Greg Weed",
    requestFrom: "Teacher",
    dateReceived: "Jul 16 2025",
    program: "Preliminary MMSN/MMD",
    nature: "I am requesting a copy of my iCAAP transcript. I might be an issue since I am not in the program and didn't complete it, short of submitting my Cal TPA2. Please feel free to contact with any questions.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1194400",
    name: "Jean-Marc Berne",
    requestFrom: "Teacher",
    dateReceived: "Jul 28 2025",
    program: "AA/BiLAA",
    nature: "I hope you had a great weekend! Thank you for taking the time to speak with me last week regarding receiving my transcript for the BiLAA program I completed last year. As suggested, I am attaching a transcript request to this email. Please confirm receipt when you get a chance. Thanks!",
    adviser: "Zina Dixon",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "Sent to catherinecummings@ccusd.org",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Culver City Unified School District"
  },
  {
    en: "1140785",
    name: "Erin Nassir",
    requestFrom: "Teacher",
    dateReceived: "Jul 20 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Hello, I am requesting my iCAAP transcripts to be sent to Pasadena USD and another copy to myself.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "Sent to ELLERBROCK.AMY@PUSD.US",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "PASADENA USD"
  },
  {
    en: "787072",
    name: "Teresa Palmer",
    requestFrom: "Teacher",
    dateReceived: "Jul 30 2025",
    program: "Preliminary Multiple Subject",
    nature: "",
    adviser: "Rene Gaudet",
    dateSent: "Aug 12 2025",
    by: "J. Detar",
    notes: "Sent to m.Rubin@bcchs.net",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Birmingham Community Charter High School"
  },
  {
    en: "690210",
    name: "Candise Ketcham Partington",
    requestFrom: "Teacher",
    dateReceived: "Jun 06 2025",
    program: "CENTSE",
    nature: "Hello- I have included my transcript request form. Thank you- Candise Partington",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 11 2025",
    by: "J. Detar",
    notes: "Sent to ascher@ccs.k12.in.us",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Carmel Clay Schools"
  },
  {
    en: "710184",
    name: "Angella Copley",
    requestFrom: "Teacher",
    dateReceived: "Jun 18 2025",
    program: "Preliminary Multiple Subject",
    nature: "",
    adviser: "Rene Gaudet",
    dateSent: "Aug 12 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1172962",
    name: "Angelica Ortiz",
    requestFrom: "Teacher",
    dateReceived: "Aug 01 2025",
    program: "Preliminary Multiple Subject",
    nature: "Hi Jennifer, I'm requesting an expedite on this transcript request. This person has a background history that warrants special attention. Thank you for your consideration. -Bonnie",
    adviser: "Rene Gaudet",
    dateSent: "Aug 12 2025",
    by: "J. Detar",
    notes: "Sent to fpeliz@fullerton.edu",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Cal State Fullerton"
  },
  {
    en: "1156197",
    name: "Michelle Cherner",
    requestFrom: "Teacher",
    dateReceived: "Aug 02 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Hello, I would like my unofficial iCAAP transcripts, please.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Aug 08 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1107828",
    name: "Hector Garcia, Jr.",
    requestFrom: "Teacher",
    dateReceived: "Aug 07 2025",
    program: "CENTSE",
    nature: "Requesting assistance or contact information regarding his DI transcript. He submitted the transcript request form in May via both email and mail but has not received any response. He needs the transcript to add an additional credential.",
    adviser: "Eberardo Rodriguez",
    dateSent: "",
    by: "",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "636247",
    name: "Cesar Gaytan",
    requestFrom: "Teacher",
    dateReceived: "Aug 10 2025",
    program: "Preliminary Multiple Subject",
    nature: "Dear Jennifer, Please send a copy of my transcript to kimroot-picq@antiochschools.net. I am attaching the form. With much appreciation, cg",
    adviser: "Rene Gaudet",
    dateSent: "Aug 12 2025",
    by: "J. Detar",
    notes: "Sent to kimroot-picq@antiochschools.net",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Antioch Unified School District"
  },
  {
    en: "",
    name: "Jillian Flynn",
    requestFrom: "Teacher",
    dateReceived: "Aug 29 2025",
    program: "Preliminary Multiple Subject",
    nature: "Hi, I sent a request for the transcript of my course of study from the LAUSD Intern Program on July 9th and have not received a response. I graduated from the program in June of 2000. I have attached a copy of my transcript request as well as a copy of my program certificate. I was wondering if you could provide me with an update on this request. Please let me know if you have any questions or require additional information. Thank you, Jillian Flynn",
    adviser: "Rene Gaudet",
    dateSent: "Sep 15 2025",
    by: "J. Detar",
    notes: "Sent to Teacher",
    dateReturnAdviser: "Sep 08 2025",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "614801",
    name: "Sarah Tracey",
    requestFrom: "Teacher",
    dateReceived: "Sep 21 2025",
    program: "Preliminary Multiple Subject",
    nature: "I am attaching the filled in form. The UK is asking for the official certificate of qualification and transcript as well as the certificate for my teaching qualification. They noted, they do not require the teaching license from the California Education Department, as this is not a qualification. Does that make sense to you? I really appreciate the help as they are trying to close my case.",
    adviser: "Rene Gaudet",
    dateSent: "Sep 22 2025",
    by: "J. Detar",
    notes: "Asked Brenda for P-Card",
    dateReturnAdviser: "Sep 22 2025",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "",
    name: "Makaila Hernandez",
    requestFrom: "Teacher",
    dateReceived: "Aug 27 2025",
    program: "",
    nature: "",
    adviser: "",
    dateSent: "Sep 08 2025",
    by: "J. Detar",
    notes: "Sent link to request transcript",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "",
    name: "Emma Schaedel",
    requestFrom: "Teacher",
    dateReceived: "Aug 26 2025",
    program: "Induction Program",
    nature: "",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Sep 05 2025",
    by: "J. Detar",
    notes: "Sent to Maikai, asking for Transcript",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1221141",
    name: "Esteban Arteaga",
    requestFrom: "Teacher",
    dateReceived: "Aug 21 2025",
    program: "Preliminary Single Subject",
    nature: "",
    adviser: "Zina Dixon",
    dateSent: "Sep 05 2025",
    by: "J. Detar",
    notes: "Esteban Arteaga did not complete iCAAP Induction program, they completed Induction with TGI. I forward their request to Christina Mendez in TGI last week. - Wendy",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1083359",
    name: "April Sequeda",
    requestFrom: "Teacher",
    dateReceived: "",
    program: "Preliminary Multiple Subject",
    nature: "",
    adviser: "Rene Gaudet",
    dateSent: "Aug 05 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Cal State Long Beach"
  },
  {
    en: "624775",
    name: "Rona Goldberg",
    requestFrom: "Teacher",
    dateReceived: "Sep 19 2025",
    program: "Preliminary Multiple Subject",
    nature: "I am requesting my transcripts from LAUSD intern program. I don't recall the actual years I was in. Most likely 1999-2001? My name at time was Rona Barthelemy. Thank you.",
    adviser: "Rene Gaudet",
    dateSent: "Sep 20 2025",
    by: "J. Detar",
    notes: "Sent to teacher",
    dateReturnAdviser: "Sep 22 2025",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "957604",
    name: "Greg Weed",
    requestFrom: "Teacher",
    dateReceived: "Sep 05 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Here is my request for my transcript.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Sep 08 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "931446",
    name: "Israel Garcia",
    requestFrom: "Hamptonie, Danita",
    dateReceived: "Sep 24 2025",
    program: "Preliminary MMSN/MMD",
    nature: "We are processing units for the above mentioned employee and noticed that the latter transcript does NOT have SPED 500 listed. Could you please review/update if the employee earned these units.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Sep 24 2025",
    by: "J. Detar",
    notes: "Sent to Eberardo for clarification",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Hamptonie, Danita"
  },
  {
    en: "1208260",
    name: "Kevin Lezak",
    requestFrom: "Teacher",
    dateReceived: "Sep 16 2025",
    program: "Preliminary Single Subject",
    nature: "Hello. I was a district intern for the 2024-25 school year and would like a copy of my transcript. Please find my request form attached. Thank you!",
    adviser: "Zina Dixon",
    dateSent: "Sep 22 2025",
    by: "J. Detar",
    notes: "Sent to mpimienta@teachps.org TEACH Public Schools",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1201073",
    name: "Oscar Blas",
    requestFrom: "Teacher",
    dateReceived: "Sep 02 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Hello! Attached is my transcript request. If you could please let me know when it has been sent out. Email to: apply@umassglobal.edu Thank you! Oscar Blas",
    adviser: "Eberardo Rodriguez",
    dateSent: "Sep 23 2025",
    by: "J. Detar",
    notes: "Sent to apply@umassglobal.edu UMass Global",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "785494",
    name: "Sandra Delgado",
    requestFrom: "Teacher",
    dateReceived: "Sep 11 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Please see attached request form for transcripts. Thank you, Sandra Delgado.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Sep 22 2025",
    by: "J. Detar",
    notes: "Katrina Granado, 562-907-5961 kgranado@ewcsd.org East Whittier City School District",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "638693",
    name: "Sarah Shiva",
    requestFrom: "Teacher",
    dateReceived: "Sep 02 2025",
    program: "AA/RLAA",
    nature: "They've completed half of their RLAA coursework and are requesting a copy of their transcript for their records. They attached the transcript request form and expressed thanks.",
    adviser: "Wendy Marrero & Rene Gaudet",
    dateSent: "Sep 08 2025",
    by: "J. Detar",
    notes: "Mailed 9/8 via snail mail",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1166875",
    name: "Sufyan Tootla",
    requestFrom: "Teacher",
    dateReceived: "Sep 04 2025",
    program: "Induction Program",
    nature: "I hope you are doing well. I am just attaching this request for a transcript. Please let me know if I need to add anything else to this in order to receive my transcript.",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Sep 19 2025",
    by: "J. Detar",
    notes: "Sent to kgranado@ewcsd.org",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "804512",
    name: "Tana Tea",
    requestFrom: "Teacher",
    dateReceived: "Sep 05 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Thank you for your help earlier. I do not see how I could add my signature on the form, please accept this email request as my signature.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Sep 22 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "",
    name: "Alondra Chavez",
    requestFrom: "Teacher",
    dateReceived: "Sep 24 2025",
    program: "Preliminary Multiple Subject",
    nature: "I've attached the transcript form to this email. Would like to get proof of PSO, pre-service orientation to keep working at the job site I am currently working in.",
    adviser: "Rene Gaudet",
    dateSent: "Sep 24 2025",
    by: "J. Detar",
    notes: "Sent to Alondra Chavez and Pamela Carriel",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "782671",
    name: "Ashley Urrieta",
    requestFrom: "Mejia, Maria",
    dateReceived: "Sep 24 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Please see attached transcripts for Ashley Urrieta 782671. The first transcript included the courses below and the second transcript does not. Can you please advise.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Sep 24 2025",
    by: "J. Detar",
    notes: "Sent to Eberardo for clarification",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1223987",
    name: "Colleen Gwin",
    requestFrom: "Teacher",
    dateReceived: "Sep 24 2025",
    program: "Preliminary Single Subject",
    nature: "Hello, I completed the summer PSO through iCAAP and attached is my transcript request. Thank you. Sincerely, Colleen Gwin",
    adviser: "Zina Dixon",
    dateSent: "Sep 25 2025",
    by: "J. Detar",
    notes: "Sent to teacher",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1047349",
    name: "Vernesha Thomas",
    requestFrom: "Teacher",
    dateReceived: "Sep 25 2025",
    program: "Preliminary Multiple Subject",
    nature: "Attached please find my transcript request form.",
    adviser: "Rene Gaudet",
    dateSent: "Oct 17 2025",
    by: "J. Detar",
    notes: "Sent to vmosby@compton.k12.ca.us at Compton Unified School District",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1155426",
    name: "Jennifer Martinez",
    requestFrom: "Teacher",
    dateReceived: "Sep 26 2025",
    program: "Induction Program",
    nature: "Below is the form for transcript request for induction. Thank you so much for your time.",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Oct 17 2025",
    by: "J. Detar",
    notes: "Sent to sloera@rcoe.us at Riverside County Office of Education",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "713860",
    name: "Trent Hall",
    requestFrom: "Teacher",
    dateReceived: "Oct 17 2025",
    program: "Preliminary Single Subject",
    nature: "I am applying for a Teaching License in Minnesota. They asked for a sealed official transcript, but they want it sent to me so I can include it in a packet and they need the verification form for the credential filled out as well that I attached. Thank you for your attention to this matter.",
    adviser: "Zina Dixon",
    dateSent: "Oct 22 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "734818",
    name: "Desiree Hutchinson",
    requestFrom: "Teacher",
    dateReceived: "Nov 09 2025",
    program: "Preliminary Multiple Subject",
    nature: "Good morning, I have been trying to request an official transcript or progress report for the iCAAP program. I need this so so can continue my classes to receive my credentials.",
    adviser: "Rene Gaudet",
    dateSent: "Nov 10 2025",
    by: "J. Detar",
    notes: "Sent to Esther Duran eduran@lapedu",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1115307",
    name: "Joseph Waybright",
    requestFrom: "Mejia, Maria",
    dateReceived: "Nov 10 2025",
    program: "Preliminary ECSE",
    nature: "",
    adviser: "Eberardo Rodriguez",
    dateSent: "Nov 10 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Mejia, Maria"
  },
  {
    en: "735110",
    name: "Bernard Rugayan",
    requestFrom: "Staff",
    dateReceived: "Nov 03 2025",
    program: "Induction Program",
    nature: "Attached is Bernard Rugayan's transcript (EN 0073510). As noted, only the second year of induction appears on the transcript. Mr. Rugayan completed his first year of induction with the Orange County Department of Education. With the submission of this transcript, please inform Salary Allocation that LAUSD and DI portions have been addressed.",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Nov 14 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "Nov 14 2025",
    dateReturnSalary: "",
    sentTo: "Rito, Veronica"
  },
  {
    en: "1158197",
    name: "Michelle Cherner",
    requestFrom: "Teacher",
    dateReceived: "Nov 09 2025",
    program: "Induction Program",
    nature: "I am requesting a copy of my unofficial transcripts for iCAAP when you have the chance. Attached is the form completed. Thank you!",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Nov 14 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "968805",
    name: "Juan Tobar",
    requestFrom: "Mejia, Maria",
    dateReceived: "Nov 17 2025",
    program: "Preliminary MMSN/MMD",
    nature: "Can you please provide me with all the official transcripts for M. Tobar? I have the below dates, although it seems as if we are missing one transcript. 07/24/2023 02/14/2024 10/25/2024 01/07/2025.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Nov 17 2025",
    by: "J. Detar",
    notes: "",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Mejia, Maria"
  },
  {
    en: "698799",
    name: "LaToya Williams",
    requestFrom: "Mejia, Maria",
    dateReceived: "Nov 03 2025",
    program: "Preliminary Multiple Subject",
    nature: "07/10/2025. The courses below do not reflect, and these were included on the first two transcripts attached dated 01/05/2023 & 07/13/2023. Please advise. EED 652 - 1 salary point - completion date 11/15/2021; EED 409 - 1 salary point - completion.",
    adviser: "Eberardo Rodriguez",
    dateSent: "Dec 12 2025",
    by: "J. Detar",
    notes: "Sent to Eberardo",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "981900",
    name: "Fabiola Alvarez",
    requestFrom: "Teacher",
    dateReceived: "Nov 06 2025",
    program: "Induction Program",
    nature: "I was informed you may be able to assist with the attached transcript request form. Please let me know if there is anything else I need to do.",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Dec 12 2025",
    by: "J. Detar",
    notes: "Sent to vmosby@compton.k12.ca.us",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "Compton Unified"
  },
  {
    en: "1153218",
    name: "Alma Bocanegra",
    requestFrom: "Teacher",
    dateReceived: "Dec 01 2025",
    program: "Induction Program",
    nature: "I completed the iCAAP preliminary credential program and also cleared my credential via iCAAP (employee ID 1153218). I would like to request my transcript (or completion record) to submit for a graduate program application. I have attached the transcript request form to this email. Thank you for your assistance.",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Dec 12 2025",
    by: "J. Detar",
    notes: "Sent email to etranscript@sjsu.edu",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "San Jose State University"
  },
  {
    en: "683810",
    name: "Jin Hee Kim",
    requestFrom: "Teacher",
    dateReceived: "Dec 02 2025",
    program: "",
    nature: "Requesting an official transcript from the LAUSD District Intern Program for employment verification. Notes a name change from Jin Hee Kim (during LAUSD employment) to Jin Kim Chang. Asks that the transcript be sent directly to recruiting@liberty.edu, with the subject line including either name, and offers to provide any additional information needed.",
    adviser: "",
    dateSent: "",
    by: "",
    notes: "Requested P-Card from Brenda",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: ""
  },
  {
    en: "1147418",
    name: "Katty Zacarias Torreblanca",
    requestFrom: "Teacher",
    dateReceived: "Dec 04 2025",
    program: "Induction Program",
    nature: "Please find attached two official transcript request forms. One transcript is for my personal records, and the second is designated for submission to California State University, Dominguez Hills (CSUDH). Thank you for your assistance with this matter. Sincerely, Katty Zacarias ID: 1147418",
    adviser: "Maikai Finnell & Wendy Marrero",
    dateSent: "Dec 12 2025",
    by: "J. Detar",
    notes: "Sent to jcombs7@csudh.edu",
    dateReturnAdviser: "",
    dateReturnSalary: "",
    sentTo: "CSUDH"
  }
];
