# Generated by Django 4.2.27 on 2026-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalDates",
            fields=[
                (
                    "name",
                    models.TextField(
                        db_column="Name", primary_key=True, serialize=False
                    ),
                ),
                ("jul", models.TextField(db_column="Jul")),
                ("aug", models.TextField(db_column="Aug")),
                ("sep", models.TextField(db_column="Sep")),
                ("oct", models.TextField(db_column="Oct")),
                ("nov", models.TextField(db_column="Nov")),
                ("dec", models.TextField(db_column="Dec")),
            ],
            options={
                "db_table": "approval_dates",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("author", models.TextField(blank=True, null=True)),
                ("completed", models.BooleanField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "books",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CalendarByDate",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("title", models.TextField()),
                ("category", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "calendar_by_date",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CalendarRecurring",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("frequency", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("pattern", models.TextField(blank=True, null=True)),
                ("day_of_month", models.IntegerField(blank=True, null=True)),
                ("weekdays", models.TextField(blank=True, null=True)),
                ("skip_months", models.TextField(blank=True, null=True)),
                ("skip_holidays", models.BooleanField(blank=True, null=True)),
                ("skip_dates", models.TextField(blank=True, null=True)),
                ("holiday_rule", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "calendar_recurring",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CheckBreakdown",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "account",
                    models.TextField(blank=True, db_column="Account", null=True),
                ),
                (
                    "number_2025_07_08",
                    models.TextField(blank=True, db_column="2025 07 08", null=True),
                ),
                (
                    "number_2025_07_23",
                    models.TextField(blank=True, db_column="2025 07 23", null=True),
                ),
                (
                    "number_2025_08_08",
                    models.TextField(blank=True, db_column="2025 08 08", null=True),
                ),
                (
                    "number_2025_08_23",
                    models.TextField(blank=True, db_column="2025 08 23", null=True),
                ),
                (
                    "sep_08_2025",
                    models.TextField(blank=True, db_column="Sep 08 2025", null=True),
                ),
                (
                    "number_2025_09_23",
                    models.TextField(blank=True, db_column="2025 09 23", null=True),
                ),
                (
                    "number_2025_10_08",
                    models.TextField(blank=True, db_column="2025 10 08", null=True),
                ),
                (
                    "number_2025_10_23",
                    models.TextField(blank=True, db_column="2025 10 23", null=True),
                ),
                (
                    "number_2025_11_08",
                    models.TextField(blank=True, db_column="2025 11 08", null=True),
                ),
                (
                    "number_2025_11_23",
                    models.TextField(blank=True, db_column="2025 11 23", null=True),
                ),
                (
                    "number_2025_12_08",
                    models.TextField(blank=True, db_column="2025 12 08", null=True),
                ),
                (
                    "number_2025_12_23",
                    models.TextField(blank=True, db_column="2025 12 23", null=True),
                ),
                (
                    "number_2026_01_08",
                    models.TextField(blank=True, db_column="2026 01 08", null=True),
                ),
                (
                    "number_2026_01_23",
                    models.TextField(blank=True, db_column="2026 01 23", null=True),
                ),
                (
                    "number_2026_02_08",
                    models.TextField(blank=True, db_column="2026 02 08", null=True),
                ),
                (
                    "number_2026_02_23",
                    models.TextField(blank=True, db_column="2026 02 23", null=True),
                ),
                (
                    "number_2026_03_08",
                    models.TextField(blank=True, db_column="2026 03 08", null=True),
                ),
                (
                    "number_2026_04_23",
                    models.TextField(blank=True, db_column="2026 04 23", null=True),
                ),
                (
                    "number_2026_05_08",
                    models.TextField(blank=True, db_column="2026 05 08", null=True),
                ),
                (
                    "number_2026_05_23",
                    models.TextField(blank=True, db_column="2026 05 23", null=True),
                ),
                (
                    "number_2026_06_08",
                    models.TextField(blank=True, db_column="2026 06 08", null=True),
                ),
                (
                    "number_2026_06_23",
                    models.TextField(blank=True, db_column="2026 06 23", null=True),
                ),
            ],
            options={
                "db_table": "Check Breakdown",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Goals",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField(unique=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("specific", models.TextField(blank=True, null=True)),
                ("measurable", models.TextField(blank=True, null=True)),
                ("achievable", models.TextField(blank=True, null=True)),
                ("relevant", models.TextField(blank=True, null=True)),
                ("timebound", models.TextField(blank=True, null=True)),
                ("statement", models.TextField(blank=True, null=True)),
                ("weekly_tasks", models.TextField(blank=True, null=True)),
                ("ties_to", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "goals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HoaExpenses",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("vendor", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("insights", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "hoa_expenses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HoursWorked",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "jul",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "aug",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "sep",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "oct",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "nov",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "dec",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "jan",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "feb",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "mar",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "apr",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "may",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "jun",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "hours_worked",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaxCompletionTimes",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("jul", models.TextField(blank=True, null=True)),
                ("aug", models.TextField(blank=True, null=True)),
                ("sep", models.TextField(blank=True, null=True)),
                ("oct", models.TextField(blank=True, null=True)),
                ("nov", models.TextField(blank=True, null=True)),
                ("dec", models.TextField(blank=True, null=True)),
                ("jan", models.TextField(blank=True, null=True)),
                ("feb", models.TextField(blank=True, null=True)),
                ("mar", models.TextField(blank=True, null=True)),
                ("apr", models.TextField(blank=True, null=True)),
                ("may", models.TextField(blank=True, null=True)),
                ("jun", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "max_completion_times",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OpusGoals",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("mission_alignment", models.TextField(blank=True, null=True)),
                ("timeframe", models.TextField(blank=True, null=True)),
                ("linked_task_ids", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                (
                    "progress_percent",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "opus_goals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OpusMasterTasks",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("linked_goal_ids", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("scheduled_task_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "opus_master_tasks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OpusMeetings",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("attendees", models.TextField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("linked_task_ids", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "opus_meetings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OpusMission",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("statement", models.TextField(blank=True, null=True)),
                ("values", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                "db_table": "opus_mission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OpusNotes",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("date", models.DateField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "opus_notes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OpusPreferences",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("theme", models.TextField(blank=True, null=True)),
                ("default_view", models.TextField(blank=True, null=True)),
                ("work_start_hour", models.IntegerField(blank=True, null=True)),
                ("work_end_hour", models.IntegerField(blank=True, null=True)),
                ("week_start_day", models.TextField(blank=True, null=True)),
                ("notifications", models.BooleanField(blank=True, null=True)),
                ("time_format", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                "db_table": "opus_preferences",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OpusTasks",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("due_time", models.TimeField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("completed", models.BooleanField(blank=True, null=True)),
                ("linked_goal_ids", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("subtasks", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "opus_tasks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "tasks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VisionBoardPhotos",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("url", models.TextField()),
                ("category", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "vision_board_photos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WorkPlannerEdits",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("date_key", models.TextField()),
                ("slot_key", models.TextField()),
                ("value", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "work_planner_edits",
                "managed": False,
            },
        ),
    ]
